/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Login from "@/Login";
import Footer from "@/Footer";
import MainHome from "./Pages/Home";
import WhatsNewReleaseNotes from "./Pages/What's_New-Release_Notes";
import WhatsNewResearch from "./Pages/What's_New-Resarch";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
            <MainHome></MainHome>
            {/* <WhatsNewReleaseNotes/> */}
            {/* <WhatsNewResearch></WhatsNewResearch> */}
      </body>
    </html>
  );
}
